# Generated by Django 5.2.10 on 2026-02-11 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0002_officeordercounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Generated Document', 'verbose_name_plural': 'Generated Documents'},
        ),
        migrations.RemoveField(
            model_name='documentlog',
            name='content',
        ),
        migrations.AddField(
            model_name='documentlog',
            name='body',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='documentlog',
            name='date_issued',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='documentlog',
            name='from_designation',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='documentlog',
            name='subject',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documentlog',
            name='to_recipients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documentlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='documentlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documentlog',
            name='document_type',
            field=models.CharField(choices=[('Office Order', 'Office Order'), ('Notice', 'Notice'), ('Circular', 'Circular'), ('Policy', 'Policy'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documentlog',
            name='language',
            field=models.CharField(default='en', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentlog',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
